### ISSUE TITLE
Use non-profit conference site for testing/demo?

### ISSUE THREAD

**Issue by charlieartist** [Monotype/Monotype_prototype_variable_fonts#8]
Good morning,
I'm currently working on the design for a conference site, which completely volunteer driven. Based on the EULA, would it be possible to use these prototype fonts there?

**Comment by Scotchester** [comment]
@bill-monotype Would the EULA permit using this on a U.S. federal government website? If not, any idea when this will be made available to Fonts.com subscribers?

**Comment by bill-monotype** [comment]
@Scotchester Sorry for the delayed response... this current version of the font has a reduced character set and is intended as a demo for testing and evaluation. Our goal was to give something to developers to start playing with, and to learn more about Variable fonts through user feedback. So the EULA has restrictions in it that would limit your use to deploy it on a live website. We did this because these are our first Variable fonts and we are still working on the tools to make Variable fonts. 

Monotype is working on commercial versions, but we have no announcements planned at this time. Please feel free to contact the Monotype sales team, and they can discuss a potential option to provide you with a commercial version through either your Fonts.com account or through an offline process.  (go to https://www.monotype.com/ and click on 'speak to sales' to fill in a form for someone to contact you)

Hope this helps!  Bill

**Comment by Scotchester** [comment]
@bill-monotype It does, thanks. I'll probably get in touch with the sales team. Thanks, Bill!

**Comment by drchae84** [comment]
Hi @bill-monotype I am also working on a small site for a local artist-run non-profit gallery. We'd love to use Kairo for the site, but wondering if this kind of thing violates monotypes EULA contract. Please let us know. Our design really utilizes the variable width feature and it'd be lovely to try and test it out on a small site like this. Thank you!

**Comment by bill-monotype** [comment]
Hi James - unfortunately the EULA for these prototype fonts prevent usage for what you want. Monotype would like to support your use for this non-profit, so let me see what we can do. I'll send you a direct message. Cheers, Bill

**Comment by drchae84** [comment]
@bill-monotype Thanks Bill! Yes, please let me know. Appreciate the quick response.

**Comment by taylorb-monotype** [comment]
The license for these fonts has expired. Please check MyFonts.com for how to purchase a license for Avenir Next and other variable fonts.
